{{- if .Values.postgresql.deploy }}
{{- if .Values.postgresql.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "urdep.postgresqlName" . }}
  namespace: {{ include "urdep.namespaceName" . }}
  labels:
    {{- include "urdep.labels" . | nindent 4 }}
data:
  database-name: {{ .Values.postgresql.database | b64enc }}
  database-password: {{ .Values.postgresql.password | b64enc }}
  database-user: {{ .Values.postgresql.user | b64enc }}
{{- else if .Values.postgresql.generatePassword }}
apiVersion: secretgenerator.mittwald.de/v1alpha1
kind: StringSecret
metadata:
  name: {{ include "urdep.postgresqlName" . }}
  namespace: {{ include "urdep.namespaceName" . }}
  {{- if .Values.odo.enable }}
  annotations:
    devfile.io/mount-path: /etc/secret/pgsql
  {{- end }}
  labels:
    {{- include "urdep.labels" . | nindent 4 }}
    {{- if .Values.odo.enable }}
    devfile.io/auto-mount: "true"
    {{- end }}
spec:
  data:
    database-name: {{ .Values.postgresql.databaseName }}
    database-user: {{ .Values.postgresql.user }}
  forceRegenerate: false
  fields:
  - fieldName: database-password
    encoding: base32
    length: "32"
{{- end }}
{{- end }}
