{{- if .Values.postgresql.deploy }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "urdep.postgresqlName" . }}
  namespace: {{ include "urdep.namespaceName" . }}
  labels:
    {{- include "urdep.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    {{- include "urdep.postgresqlSelectorLabels" . | nindent 4 }}
{{- end }}
