"""initial

Revision ID: ab9d036fdde9
Revises: 
Create Date: 2024-09-18 20:31:32.579552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_function import PGFunction
from sqlalchemy import text as sql_text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab9d036fdde9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urdep_actuator',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Unique name'),
    sa.Column('uuid', sa.Uuid(), server_default=sa.text('GEN_RANDOM_UUID()'), nullable=False, comment='Unique identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(NOW() AT TIME ZONE 'utc')"), nullable=False, comment='Creation timestamp'),
    sa.CheckConstraint("(name ~ '^[A-Za-z]([A-Za-z0-9\\-.]*[A-Za-z0-9])?$')", name='name_format'),
    sa.PrimaryKeyConstraint('uuid'),
    schema='public',
    comment='Actuators are configured by governors to perform actions for subjects'
    )
    op.create_index(op.f('ix_public_urdep_actuator_name'), 'urdep_actuator', ['name'], unique=True, schema='public')
    op.create_table('urdep_actuator_token',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Unique name'),
    sa.Column('uuid', sa.Uuid(), server_default=sa.text('GEN_RANDOM_UUID()'), nullable=False, comment='Unique identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(NOW() AT TIME ZONE 'utc')"), nullable=False, comment='Creation timestamp'),
    sa.CheckConstraint("(name ~ '^[A-Za-z]([A-Za-z0-9\\-.]*[A-Za-z0-9])?$')", name='name_format'),
    sa.PrimaryKeyConstraint('uuid'),
    schema='public',
    comment='Actuator access token for API access'
    )
    op.create_index(op.f('ix_public_urdep_actuator_token_name'), 'urdep_actuator_token', ['name'], unique=True, schema='public')
    op.create_table('urdep_governor',
    sa.Column('provision_actuator_uuid', sa.Uuid(), nullable=True),
    sa.Column('start_actuator_uuid', sa.Uuid(), nullable=True),
    sa.Column('stop_actuator_uuid', sa.Uuid(), nullable=True),
    sa.Column('status_actuator_uuid', sa.Uuid(), nullable=True),
    sa.Column('destroy_actuator_uuid', sa.Uuid(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('vars', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('namespace', sa.String(length=255), nullable=False, comment='Namespace for context with name'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Unique name within namespace'),
    sa.Column('uuid', sa.Uuid(), server_default=sa.text('GEN_RANDOM_UUID()'), nullable=False, comment='Unique identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(NOW() AT TIME ZONE 'utc')"), nullable=False, comment='Creation timestamp'),
    sa.CheckConstraint("(name ~ '^[A-Za-z]([A-Za-z0-9\\-.]*[A-Za-z0-9])?$')", name='name_format'),
    sa.CheckConstraint("(namespace ~ '^[A-Za-z]([A-Za-z0-9\\-.]*[A-Za-z0-9])?$')", name='namespace_format'),
    sa.ForeignKeyConstraint(['destroy_actuator_uuid'], ['public.urdep_actuator.uuid'], ),
    sa.ForeignKeyConstraint(['provision_actuator_uuid'], ['public.urdep_actuator.uuid'], ),
    sa.ForeignKeyConstraint(['start_actuator_uuid'], ['public.urdep_actuator.uuid'], ),
    sa.ForeignKeyConstraint(['status_actuator_uuid'], ['public.urdep_actuator.uuid'], ),
    sa.ForeignKeyConstraint(['stop_actuator_uuid'], ['public.urdep_actuator.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('namespace', 'name', name='urdep_governor_namespace_name'),
    schema='public',
    comment='governors configure management of subjects'
    )
    op.create_index(op.f('ix_public_urdep_governor_name'), 'urdep_governor', ['name'], unique=False, schema='public')
    op.create_index(op.f('ix_public_urdep_governor_namespace'), 'urdep_governor', ['namespace'], unique=False, schema='public')
    op.create_table('public.urdep_governor_component',
    sa.Column('governor_uuid', sa.Uuid(), nullable=False),
    sa.Column('linked_governor_uuid', sa.Uuid(), nullable=False),
    sa.Column('provision_handling', sa.Enum('before', 'after', 'delegate', 'disable', name='urdep_governor_component_action_handling', inherit_schema=True, create_constraint=True), nullable=False),
    sa.Column('start_handling', sa.Enum('before', 'after', 'delegate', 'disable', name='urdep_governor_component_action_handling', inherit_schema=True, create_constraint=True), nullable=False),
    sa.Column('stop_handling', sa.Enum('before', 'after', 'delegate', 'disable', name='urdep_governor_component_action_handling', inherit_schema=True, create_constraint=True), nullable=False),
    sa.Column('status_handling', sa.Enum('before', 'after', 'delegate', 'disable', name='urdep_governor_component_action_handling', create_constraint=True), nullable=False),
    sa.Column('destroy_handling', sa.Enum('before', 'after', 'delegate', 'disable', name='urdep_governor_component_action_handling', create_constraint=True), nullable=False),
    sa.Column('uuid', sa.Uuid(), server_default=sa.text('GEN_RANDOM_UUID()'), nullable=False, comment='Unique identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(NOW() AT TIME ZONE 'utc')"), nullable=False, comment='Creation timestamp'),
    sa.ForeignKeyConstraint(['governor_uuid'], ['public.urdep_governor.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['linked_governor_uuid'], ['public.urdep_governor.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('urdep_subject',
    sa.Column('governor_uuid', sa.Uuid(), nullable=False, comment='governor configures how the subject is managed'),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('vars', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('current_state', sa.Enum('new', 'provision-waiting', 'provision-pending', 'provisioning', 'provision-failed', 'start-waiting', 'start-pending', 'starting', 'start-failed', 'started', 'stop-waiting', 'stop-pending', 'stopping', 'stop-failed', 'stopped', 'destroy-waiting', 'destroy-pending', 'destroying', 'destroy-failed', 'destroyed', name='urdep_subject_current_state', schema='public', inherit_schema=True, create_constraint=True), server_default='new', nullable=False),
    sa.Column('desired_state', sa.Enum('started', 'stopped', 'destroyed', name='urdep_subject_desired_state', schema='public', inherit_schema=True, create_constraint=True), server_default='started', nullable=False),
    sa.Column('provision_began', sa.DateTime(timezone=True), nullable=True, comment='when provision handling began'),
    sa.Column('provision_completed', sa.DateTime(timezone=True), nullable=True, comment='when provision completed'),
    sa.Column('provision_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('provision_messages', sa.Text(), nullable=True),
    sa.Column('start_began', sa.DateTime(timezone=True), nullable=True, comment='when last start handling began'),
    sa.Column('start_completed', sa.DateTime(timezone=True), nullable=True, comment='when last start completed'),
    sa.Column('start_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('start_messages', sa.Text(), nullable=True),
    sa.Column('stop_began', sa.DateTime(timezone=True), nullable=True, comment='when last stop handling began'),
    sa.Column('stop_completed', sa.DateTime(timezone=True), nullable=True, comment='when last stop completed'),
    sa.Column('stop_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stop_messages', sa.Text(), nullable=True),
    sa.Column('status_began', sa.DateTime(timezone=True), nullable=True, comment='when last status handling began'),
    sa.Column('status_completed', sa.DateTime(timezone=True), nullable=True, comment='when last status completed'),
    sa.Column('status_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status_messages', sa.Text(), nullable=True),
    sa.Column('destroy_began', sa.DateTime(timezone=True), nullable=True, comment='when last destroy attempt began'),
    sa.Column('destroy_completed', sa.DateTime(timezone=True), nullable=True, comment='when last destroy attempt completed'),
    sa.Column('destroy_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('destroy_messages', sa.Text(), nullable=True),
    sa.Column('namespace', sa.String(length=255), nullable=False, comment='Namespace for context with name'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Unique name within namespace'),
    sa.Column('uuid', sa.Uuid(), server_default=sa.text('GEN_RANDOM_UUID()'), nullable=False, comment='Unique identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(NOW() AT TIME ZONE 'utc')"), nullable=False, comment='Creation timestamp'),
    sa.CheckConstraint("(name ~ '^[A-Za-z]([A-Za-z0-9\\-.]*[A-Za-z0-9])?$')", name='name_format'),
    sa.CheckConstraint("(namespace ~ '^[A-Za-z]([A-Za-z0-9\\-.]*[A-Za-z0-9])?$')", name='namespace_format'),
    sa.ForeignKeyConstraint(['governor_uuid'], ['public.urdep_governor.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('namespace', 'name', name='urdep_subject_namespace_name'),
    schema='public',
    comment='subjects represent anything managed by an actuator'
    )
    op.create_index(op.f('ix_public_urdep_subject_name'), 'urdep_subject', ['name'], unique=False, schema='public')
    op.create_index(op.f('ix_public_urdep_subject_namespace'), 'urdep_subject', ['namespace'], unique=False, schema='public')
    op.create_table('urdep_action',
    sa.Column('actuator_uuid', sa.Uuid(), nullable=False, comment='actuator responsible for this action'),
    sa.Column('subject_uuid', sa.Uuid(), nullable=False, comment='subject of this action'),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('vars', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actuator_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('messages', sa.Text(), nullable=True),
    sa.Column('kind', sa.Enum('provision', 'start', 'stop', 'status', 'destroy', name='urdep_action_kind', schema='public', inherit_schema=True, create_constraint=True), nullable=False),
    sa.Column('action_state', sa.Enum('new', 'waiting', 'pending', 'running', 'failed', 'successful', name='urdep_action_state', schema='public', inherit_schema=True, create_constraint=True), server_default='new', nullable=False),
    sa.Column('began', sa.DateTime(timezone=True), nullable=True, comment='when action handling began'),
    sa.Column('completed', sa.DateTime(timezone=True), nullable=True, comment='when action handling completed'),
    sa.Column('namespace', sa.String(length=255), nullable=False, comment='Namespace for context with name'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Unique name within namespace'),
    sa.Column('uuid', sa.Uuid(), server_default=sa.text('GEN_RANDOM_UUID()'), nullable=False, comment='Unique identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(NOW() AT TIME ZONE 'utc')"), nullable=False, comment='Creation timestamp'),
    sa.CheckConstraint("(name ~ '^[A-Za-z]([A-Za-z0-9\\-.]*[A-Za-z0-9])?$')", name='name_format'),
    sa.CheckConstraint("(namespace ~ '^[A-Za-z]([A-Za-z0-9\\-.]*[A-Za-z0-9])?$')", name='namespace_format'),
    sa.ForeignKeyConstraint(['actuator_uuid'], ['public.urdep_actuator.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_uuid'], ['public.urdep_subject.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('namespace', 'name', name='urdep_action_namespace_name'),
    schema='public',
    comment='actions represent provisoning and lifecycle activities for a subject'
    )
    op.create_index(op.f('ix_public_urdep_action_name'), 'urdep_action', ['name'], unique=False, schema='public')
    op.create_index(op.f('ix_public_urdep_action_namespace'), 'urdep_action', ['namespace'], unique=False, schema='public')
    public_urdep_inherit_subject_desired_state = PGFunction(
        schema="public",
        signature="urdep_inherit_subject_desired_state()",
        definition='RETURNS TRIGGER AS $$\n  BEGIN\n    IF NEW.parent_uuid IS NOT NULL THEN\n      NEW.desired_state := (SELECT desired_state FROM urdep_subject WHERE uuid=NEW.parent_uuid);\n    END IF;\n  END;\n$$ LANGUAGE plpgsql'
    )
    op.create_entity(public_urdep_inherit_subject_desired_state)

    public_urdep_propagate_subject_desired_state = PGFunction(
        schema="public",
        signature="urdep_propagate_subject_desired_state()",
        definition='RETURNS TRIGGER AS $$\n  BEGIN\n    UPDATE urdep_subject SET desired_state=NEW.desired_state WHERE uuid=NEW.uuid;\n  END;\n$$ LANGUAGE plpgsql'
    )
    op.create_entity(public_urdep_propagate_subject_desired_state)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_urdep_propagate_subject_desired_state = PGFunction(
        schema="public",
        signature="urdep_propagate_subject_desired_state()",
        definition='RETURNS TRIGGER AS $$\n  BEGIN\n    UPDATE urdep_subject SET desired_state=NEW.desired_state WHERE uuid=NEW.uuid;\n  END;\n$$ LANGUAGE plpgsql'
    )
    op.drop_entity(public_urdep_propagate_subject_desired_state)

    public_urdep_inherit_subject_desired_state = PGFunction(
        schema="public",
        signature="urdep_inherit_subject_desired_state()",
        definition='RETURNS TRIGGER AS $$\n  BEGIN\n    IF NEW.parent_uuid IS NOT NULL THEN\n      NEW.desired_state := (SELECT desired_state FROM urdep_subject WHERE uuid=NEW.parent_uuid);\n    END IF;\n  END;\n$$ LANGUAGE plpgsql'
    )
    op.drop_entity(public_urdep_inherit_subject_desired_state)

    op.drop_index(op.f('ix_public_urdep_action_namespace'), table_name='urdep_action', schema='public')
    op.drop_index(op.f('ix_public_urdep_action_name'), table_name='urdep_action', schema='public')
    op.drop_table('urdep_action', schema='public')
    op.drop_index(op.f('ix_public_urdep_subject_namespace'), table_name='urdep_subject', schema='public')
    op.drop_index(op.f('ix_public_urdep_subject_name'), table_name='urdep_subject', schema='public')
    op.drop_table('urdep_subject', schema='public')
    op.drop_table('public.urdep_governor_component')
    op.drop_index(op.f('ix_public_urdep_governor_namespace'), table_name='urdep_governor', schema='public')
    op.drop_index(op.f('ix_public_urdep_governor_name'), table_name='urdep_governor', schema='public')
    op.drop_table('urdep_governor', schema='public')
    op.drop_index(op.f('ix_public_urdep_actuator_token_name'), table_name='urdep_actuator_token', schema='public')
    op.drop_table('urdep_actuator_token', schema='public')
    op.drop_index(op.f('ix_public_urdep_actuator_name'), table_name='urdep_actuator', schema='public')
    op.drop_table('urdep_actuator', schema='public')
    # ### end Alembic commands ###
