"""triggers

Revision ID: d558d8c6d691
Revises: 2771390989f4
Create Date: 2024-09-20 16:25:40.380935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from alembic_utils.pg_trigger import PGTrigger
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision: str = 'd558d8c6d691'
down_revision: Union[str, None] = '2771390989f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_urdep_subject_urdep_inherit_subject_desired_state = PGTrigger(
        schema="public",
        signature="urdep_inherit_subject_desired_state",
        on_entity="public.urdep_subject",
        is_constraint=False,
        definition='BEFORE INSERT OR UPDATE ON urdep_subject\n  FOR EACH ROW\n  EXECUTE FUNCTION urdep_inherit_subject_desired_state()'
    )
    op.create_entity(public_urdep_subject_urdep_inherit_subject_desired_state)

    public_urdep_subject_urdep_propagate_subject_desired_state = PGTrigger(
        schema="public",
        signature="urdep_propagate_subject_desired_state",
        on_entity="public.urdep_subject",
        is_constraint=False,
        definition='AFTER INSERT OR UPDATE ON urdep_subject\n  FOR EACH ROW\n  EXECUTE FUNCTION urdep_propagate_subject_desired_state()'
    )
    op.create_entity(public_urdep_subject_urdep_propagate_subject_desired_state)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_urdep_subject_urdep_propagate_subject_desired_state = PGTrigger(
        schema="public",
        signature="urdep_propagate_subject_desired_state",
        on_entity="public.urdep_subject",
        is_constraint=False,
        definition='AFTER INSERT OR UPDATE ON urdep_subject\n  FOR EACH ROW\n  EXECUTE FUNCTION urdep_propagate_subject_desired_state()'
    )
    op.drop_entity(public_urdep_subject_urdep_propagate_subject_desired_state)

    public_urdep_subject_urdep_inherit_subject_desired_state = PGTrigger(
        schema="public",
        signature="urdep_inherit_subject_desired_state",
        on_entity="public.urdep_subject",
        is_constraint=False,
        definition='BEFORE INSERT OR UPDATE ON urdep_subject\n  FOR EACH ROW\n  EXECUTE FUNCTION urdep_inherit_subject_desired_state()'
    )
    op.drop_entity(public_urdep_subject_urdep_inherit_subject_desired_state)

    # ### end Alembic commands ###
